# =============================================
# BUILD CONFIG
# =============================================

root:             _gh_pages
dest:             <%= site.root %>
assets:           <%= site.dest %>/assets
date:             <%= new Date() %>


# Data
data:             data

# Styles
styles:           styles

# Content
content:          content

# Templates
templates:        templates
pages:            <%= site.templates %>
includes:         <%= site.templates %>/includes
layouts:          <%= site.templates %>/layouts
markedtemplates:  <%= site.templates %>/marked
layoutext:        .hbs
layout:           default

# Extensions
helpers:          <%= site.templates %>/helpers
plugins:
  - assemble-contrib-permalinks
  - templates/plugins/toc.js
  - templates/plugins/holder-404-avoid.js
#  - templates/plugins/link-checker.js

# Less.js metadata
current_version:   <%= less.version %>

# Site metadata
brand:             lesscss.org
title:             Less.js
lead:              Less Â« The Dynamic Stylesheet Language
description: >
  Less extends CSS with dynamic behavior such as variables, mixins, operations and functions.
  Less runs on both the server-side (with Node.js and Rhino) or client-side (modern browsers only).

# URLs
homepage:          http://lesscss.org
repo:              <%= pkg.repository.url %>
issues:            <%= pkg.bugs.url %>?&state=open
download:
  source:          <%= pkg.homepages %>/archive/master.zip
  latest:          https://raw.github.com/less/less.js/master/dist/less-<%= less.version %>.min.js

cdn:
  cloudflare:      //cdnjs.cloudflare.com/ajax/libs/less.js/

# SEO/SEM
analytics:
  alexa:           lpTeh1awA400OE
  google:          false
  google_site_id:  false


# Comments
disqus:
  enabled:        true
  shortname:      <%= pkg.name %>

# Social
social:
  twitter:
    via:          false
    username:     false
  facebook:       false
  linkedin:       false
  gplus:          false
  hn:             false
  google:         false

# Sharing
sharing:
  twitter:        false
  facebook:       false
  gplus:          false
  hn:             false
  google:         false