# =============================================
# BUILD CONFIG
# =============================================

root:             _gh_pages
dest:             <%= site.root %>
assets:           <%= site.dest %>/assets

# Templates
templates:        templates
pages:            <%= site.templates %>
includes:         <%= site.templates %>/includes
layouts:          <%= site.templates %>/layouts
layout:           default.hbs

# Data
data:             data

# Extensions
helpers:          <%= site.templates %>/helpers
plugins:
  - assemble-contrib-anchors
  - assemble-contrib-wordcount
  - assemble-contrib-toc


# Less.js metadata
current_version:   <%= less.version %>

# Site metadata
brand:             lesscss.org
title:             Less.js
lead:              LESS Â« The Dynamic Stylesheet Language
description: >
  LESS extends CSS with dynamic behavior such as variables, mixins, operations and functions.
  LESS runs on both the server-side (with Node.js and Rhino) or client-side (modern browsers only).

# Documentation License
license:
  type:            <%= pkg.licenses[0].type %>
  url:             <%= pkg.licenses[0].url %>

# URLs
repo:              <%= pkg.repository.url %>
issues:            <%= pkg.bugs.url %>?&state=open
download:
  source:          <%= pkg.homepages %>/archive/master.zip
  latest:          https://raw.github.com/less/less.js/master/dist/less-<%= less.version %>.min.js
coderepo:          <%= pkg.coderepository.url %>
codeissues:        <%= pkg.codebugs.url %>?&state=open
codebasemaster:    <%= pkg.codebasemaster.url %>

cdn:
  cloudflare:      //cdnjs.cloudflare.com/ajax/libs/less.js/1.5.0/less.min.js

# SEO/SEM
analytics:
  alexa:           lpTeh1awA400OE
  google:          false
  google_site_id:  false